In [20]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/sktechno710/collabspace-events/collabspace_events.csv

In [21]:
# data loading
df = pd.read_csv('/kaggle/input/datasets/sktechno710/collabspace-events/collabspace_events.csv')

In [22]:
df

       user_id  event_date    event_type
0         1000  2025-01-06         login
1         1000  2025-01-09  send_message
2         1000  2025-01-21         login
3         1000  2025-01-24   upload_file
4         1000  2025-01-25  send_message
...        ...         ...           ...
13781     1499  2025-06-11  send_message
13782     1499  2025-06-15  send_message
13783     1499  2025-06-15         login
13784     1499  2025-06-25   upload_file
13785     1499  2025-06-29         login

[13786 rows x 3 columns]

In [23]:
# Converting to pandas datetime format
df['event_date'] = pd.to_datetime(df['event_date'])

In [24]:
# Finding number of unique user id
df['user_id'].unique()

array([1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010,
       1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021,
       1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032,
       1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043,
       1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054,
       1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065,
       1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076,
       1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087,
       1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098,
       1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109,
       1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120,
       1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131,
       1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142,
       1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153,
       1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164,
       1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175,
       1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186,
       1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197,
       1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208,
       1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219,
       1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230,
       1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241,
       1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252,
       1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263,
       1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274,
       1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285,
       1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296,
       1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1307,
       1308, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318,
       1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329,
       1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340,
       1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351,
       1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362,
       1363, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1372, 1373,
       1374, 1375, 1376, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384,
       1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395,
       1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406,
       1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417,
       1418, 1419, 1420, 1421, 1422, 1423, 1424, 1425, 1426, 1427, 1428,
       1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439,
       1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450,
       1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461,
       1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472,
       1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483,
       1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494,
       1495, 1496, 1497, 1498, 1499])

In [25]:
# Extracting the last event date of user id 1001
list(df[df['user_id']==1001].tail(2)['event_date'])[1]

Timestamp('2025-06-24 00:00:00')

In [26]:
# Extracting time diff of last two activities of a specific user id
list(df[df['user_id']==1001].tail(2)['event_date'])[1] - list(df[df['user_id']==1001].tail(2)['event_date'])[0]

Timedelta('5 days 00:00:00')

In [27]:
# Creating new dataframe
new_df = pd.DataFrame(columns=['user_id', 'days_since_last_event','last_event_date'])
for id in df['user_id'].unique():
    a = list(df[df['user_id']==id].tail(2)['event_date'])[1]
    b = list(df[df['user_id']==id].tail(2)['event_date'])[0]
    new_df.loc[len(new_df)]=[id,a-b,a]

In [28]:
new_df

     user_id days_since_last_event last_event_date
0       1000                6 days      2025-04-11
1       1001                5 days      2025-06-24
2       1002                8 days      2025-04-10
3       1003                6 days      2025-06-13
4       1004                5 days      2025-03-24
..       ...                   ...             ...
495     1495               15 days      2025-06-29
496     1496                3 days      2025-06-29
497     1497                1 days      2025-04-06
498     1498                1 days      2025-06-27
499     1499                4 days      2025-06-29

[500 rows x 3 columns]

In [29]:
# No Null Value Present
print(new_df.isnull().sum())

user_id                  0
days_since_last_event    0
last_event_date          0
dtype: int64

In [30]:
# Statistically Churn_Threshold_Days is the 95th Percentile of the days since last event
Churn_Threshold_Days = new_df['days_since_last_event'].quantile(0.95)
Churn_Threshold_Days

Timedelta('17 days 00:00:00')

In [31]:
current_date = df['event_date'].max()
current_date

Timestamp('2025-06-29 00:00:00')

In [32]:
# Extracting which user is not active from more that Churn_Threshold_Days
new_df[current_date - new_df['last_event_date']>Churn_Threshold_Days]

     user_id days_since_last_event last_event_date
0       1000                6 days      2025-04-11
2       1002                8 days      2025-04-10
4       1004                5 days      2025-03-24
23      1023               15 days      2025-04-12
33      1033               31 days      2025-04-09
..       ...                   ...             ...
485     1485               12 days      2025-04-14
486     1486                4 days      2025-03-31
490     1490               12 days      2025-03-30
493     1493                2 days      2025-04-11
497     1497                1 days      2025-04-06

[115 rows x 3 columns]

In [33]:
# Making N
new_df['IsChurned'] = np.where(current_date - new_df['last_event_date']>Churn_Threshold_Days, 1, 0)

In [34]:
new_df

     user_id days_since_last_event last_event_date  IsChurned
0       1000                6 days      2025-04-11          1
1       1001                5 days      2025-06-24          0
2       1002                8 days      2025-04-10          1
3       1003                6 days      2025-06-13          0
4       1004                5 days      2025-03-24          1
..       ...                   ...             ...        ...
495     1495               15 days      2025-06-29          0
496     1496                3 days      2025-06-29          0
497     1497                1 days      2025-04-06          1
498     1498                1 days      2025-06-27          0
499     1499                4 days      2025-06-29          0

[500 rows x 4 columns]

In [35]:
new_df.to_csv('aggregate_churn.csv',index=False)